/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = lagrello.Client.OpenAPIDateConverter;

namespace lagrello.Model
{
    /// <summary>
    /// payload with the secret key and url to QR code image
    /// </summary>
    [DataContract]
    public partial class TotpEnableResponse :  IEquatable<TotpEnableResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TotpEnableResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TotpEnableResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TotpEnableResponse" /> class.
        /// </summary>
        /// <param name="secretKey">secretKey (required).</param>
        /// <param name="qrImage">qrImage (required).</param>
        public TotpEnableResponse(string secretKey = default(string), string qrImage = default(string))
        {
            // to ensure "secretKey" is required (not null)
            if (secretKey == null)
            {
                throw new InvalidDataException("secretKey is a required property for TotpEnableResponse and cannot be null");
            }
            else
            {
                this.SecretKey = secretKey;
            }

            // to ensure "qrImage" is required (not null)
            if (qrImage == null)
            {
                throw new InvalidDataException("qrImage is a required property for TotpEnableResponse and cannot be null");
            }
            else
            {
                this.QrImage = qrImage;
            }

        }

        /// <summary>
        /// Gets or Sets SecretKey
        /// </summary>
        [DataMember(Name="secretKey", EmitDefaultValue=true)]
        public string SecretKey { get; set; }

        /// <summary>
        /// Gets or Sets QrImage
        /// </summary>
        [DataMember(Name="qrImage", EmitDefaultValue=true)]
        public string QrImage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TotpEnableResponse {\n");
            sb.Append("  SecretKey: ").Append(SecretKey).Append("\n");
            sb.Append("  QrImage: ").Append(QrImage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TotpEnableResponse);
        }

        /// <summary>
        /// Returns true if TotpEnableResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TotpEnableResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TotpEnableResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SecretKey == input.SecretKey ||
                    (this.SecretKey != null &&
                    this.SecretKey.Equals(input.SecretKey))
                ) && 
                (
                    this.QrImage == input.QrImage ||
                    (this.QrImage != null &&
                    this.QrImage.Equals(input.QrImage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SecretKey != null)
                    hashCode = hashCode * 59 + this.SecretKey.GetHashCode();
                if (this.QrImage != null)
                    hashCode = hashCode * 59 + this.QrImage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
