/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using lagrello.Client;
using lagrello.Model;

namespace lagrello.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Creates a user in tenant, tenant is determined from the token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <returns>User</returns>
        User UsersCreate (CreateUserRequest createUserRequest = default(CreateUserRequest));

        /// <summary>
        /// Creates a user in tenant, tenant is determined from the token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <returns>ApiResponse of User</returns>
        ApiResponse<User> UsersCreateWithHttpInfo (CreateUserRequest createUserRequest = default(CreateUserRequest));
        /// <summary>
        /// Deletes specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to delete</param>
        /// <returns></returns>
        void UsersDelete (string userId);

        /// <summary>
        /// Deletes specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to delete</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UsersDeleteWithHttpInfo (string userId);
        /// <summary>
        /// Returns specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">userId of user you want to fetch information about</param>
        /// <returns>User</returns>
        User UsersGet (string userId);

        /// <summary>
        /// Returns specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">userId of user you want to fetch information about</param>
        /// <returns>ApiResponse of User</returns>
        ApiResponse<User> UsersGetWithHttpInfo (string userId);
        /// <summary>
        /// Updates specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to update</param>
        /// <param name="updateUserRequest"> (optional)</param>
        /// <returns>User</returns>
        User UsersUpdate (string userId, UpdateUserRequest updateUserRequest = default(UpdateUserRequest));

        /// <summary>
        /// Updates specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to update</param>
        /// <param name="updateUserRequest"> (optional)</param>
        /// <returns>ApiResponse of User</returns>
        ApiResponse<User> UsersUpdateWithHttpInfo (string userId, UpdateUserRequest updateUserRequest = default(UpdateUserRequest));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Creates a user in tenant, tenant is determined from the token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of User</returns>
        System.Threading.Tasks.Task<User> UsersCreateAsync (CreateUserRequest createUserRequest = default(CreateUserRequest), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Creates a user in tenant, tenant is determined from the token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (User)</returns>
        System.Threading.Tasks.Task<ApiResponse<User>> UsersCreateWithHttpInfoAsync (CreateUserRequest createUserRequest = default(CreateUserRequest), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Deletes specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UsersDeleteAsync (string userId, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Deletes specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UsersDeleteWithHttpInfoAsync (string userId, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Returns specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">userId of user you want to fetch information about</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of User</returns>
        System.Threading.Tasks.Task<User> UsersGetAsync (string userId, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Returns specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">userId of user you want to fetch information about</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (User)</returns>
        System.Threading.Tasks.Task<ApiResponse<User>> UsersGetWithHttpInfoAsync (string userId, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Updates specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to update</param>
        /// <param name="updateUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of User</returns>
        System.Threading.Tasks.Task<User> UsersUpdateAsync (string userId, UpdateUserRequest updateUserRequest = default(UpdateUserRequest), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Updates specified user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to update</param>
        /// <param name="updateUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (User)</returns>
        System.Threading.Tasks.Task<ApiResponse<User>> UsersUpdateWithHttpInfoAsync (string userId, UpdateUserRequest updateUserRequest = default(UpdateUserRequest), CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UsersApi : IUsersApi
    {
        private lagrello.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UsersApi(String basePath)
        {
            this.Configuration = new lagrello.Client.Configuration { BasePath = basePath };

            ExceptionFactory = lagrello.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class
        /// </summary>
        /// <returns></returns>
        public UsersApi()
        {
            this.Configuration = lagrello.Client.Configuration.Default;

            ExceptionFactory = lagrello.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UsersApi(lagrello.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = lagrello.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = lagrello.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public lagrello.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public lagrello.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Creates a user in tenant, tenant is determined from the token 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <returns>User</returns>
        public User UsersCreate (CreateUserRequest createUserRequest = default(CreateUserRequest))
        {
             ApiResponse<User> localVarResponse = UsersCreateWithHttpInfo(createUserRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a user in tenant, tenant is determined from the token 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <returns>ApiResponse of User</returns>
        public ApiResponse<User> UsersCreateWithHttpInfo (CreateUserRequest createUserRequest = default(CreateUserRequest))
        {

            var localVarPath = "/v1/users";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (createUserRequest != null && createUserRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(createUserRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = createUserRequest; // byte array
            }

            // authentication (token) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersCreate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<User>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (User) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(User)));
        }

        /// <summary>
        /// Creates a user in tenant, tenant is determined from the token 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of User</returns>
        public async System.Threading.Tasks.Task<User> UsersCreateAsync (CreateUserRequest createUserRequest = default(CreateUserRequest), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<User> localVarResponse = await UsersCreateWithHttpInfoAsync(createUserRequest, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates a user in tenant, tenant is determined from the token 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (User)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<User>> UsersCreateWithHttpInfoAsync (CreateUserRequest createUserRequest = default(CreateUserRequest), CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/v1/users";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (createUserRequest != null && createUserRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(createUserRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = createUserRequest; // byte array
            }

            // authentication (token) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersCreate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<User>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (User) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(User)));
        }

        /// <summary>
        /// Deletes specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to delete</param>
        /// <returns></returns>
        public void UsersDelete (string userId)
        {
             UsersDeleteWithHttpInfo(userId);
        }

        /// <summary>
        /// Deletes specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to delete</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> UsersDeleteWithHttpInfo (string userId)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling UsersApi->UsersDelete");

            var localVarPath = "/v1/users/{userId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter

            // authentication (token) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Deletes specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UsersDeleteAsync (string userId, CancellationToken cancellationToken = default(CancellationToken))
        {
             await UsersDeleteWithHttpInfoAsync(userId, cancellationToken);

        }

        /// <summary>
        /// Deletes specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> UsersDeleteWithHttpInfoAsync (string userId, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling UsersApi->UsersDelete");

            var localVarPath = "/v1/users/{userId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter

            // authentication (token) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Returns specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">userId of user you want to fetch information about</param>
        /// <returns>User</returns>
        public User UsersGet (string userId)
        {
             ApiResponse<User> localVarResponse = UsersGetWithHttpInfo(userId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">userId of user you want to fetch information about</param>
        /// <returns>ApiResponse of User</returns>
        public ApiResponse<User> UsersGetWithHttpInfo (string userId)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling UsersApi->UsersGet");

            var localVarPath = "/v1/users/{userId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter

            // authentication (token) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<User>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (User) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(User)));
        }

        /// <summary>
        /// Returns specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">userId of user you want to fetch information about</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of User</returns>
        public async System.Threading.Tasks.Task<User> UsersGetAsync (string userId, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<User> localVarResponse = await UsersGetWithHttpInfoAsync(userId, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">userId of user you want to fetch information about</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (User)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<User>> UsersGetWithHttpInfoAsync (string userId, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling UsersApi->UsersGet");

            var localVarPath = "/v1/users/{userId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter

            // authentication (token) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<User>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (User) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(User)));
        }

        /// <summary>
        /// Updates specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to update</param>
        /// <param name="updateUserRequest"> (optional)</param>
        /// <returns>User</returns>
        public User UsersUpdate (string userId, UpdateUserRequest updateUserRequest = default(UpdateUserRequest))
        {
             ApiResponse<User> localVarResponse = UsersUpdateWithHttpInfo(userId, updateUserRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Updates specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to update</param>
        /// <param name="updateUserRequest"> (optional)</param>
        /// <returns>ApiResponse of User</returns>
        public ApiResponse<User> UsersUpdateWithHttpInfo (string userId, UpdateUserRequest updateUserRequest = default(UpdateUserRequest))
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling UsersApi->UsersUpdate");

            var localVarPath = "/v1/users/{userId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (updateUserRequest != null && updateUserRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(updateUserRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = updateUserRequest; // byte array
            }

            // authentication (token) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersUpdate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<User>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (User) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(User)));
        }

        /// <summary>
        /// Updates specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to update</param>
        /// <param name="updateUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of User</returns>
        public async System.Threading.Tasks.Task<User> UsersUpdateAsync (string userId, UpdateUserRequest updateUserRequest = default(UpdateUserRequest), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<User> localVarResponse = await UsersUpdateWithHttpInfoAsync(userId, updateUserRequest, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Updates specified user 
        /// </summary>
        /// <exception cref="lagrello.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Id of the user you want to update</param>
        /// <param name="updateUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (User)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<User>> UsersUpdateWithHttpInfoAsync (string userId, UpdateUserRequest updateUserRequest = default(UpdateUserRequest), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling UsersApi->UsersUpdate");

            var localVarPath = "/v1/users/{userId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (updateUserRequest != null && updateUserRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(updateUserRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = updateUserRequest; // byte array
            }

            // authentication (token) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersUpdate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<User>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (User) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(User)));
        }

    }
}
