/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using lagrello.Client;
using lagrello.Api;
using lagrello.Model;

namespace lagrello.Test
{
    /// <summary>
    ///  Class for testing TokensApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TokensApiTests
    {
        private TokensApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TokensApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TokensApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' TokensApi
            //Assert.IsInstanceOf(typeof(TokensApi), instance);
        }

        
        /// <summary>
        /// Test TokensCreate
        /// </summary>
        [Test]
        public void TokensCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateTokenRequest createTokenRequest = null;
            //var response = instance.TokensCreate(createTokenRequest);
            //Assert.IsInstanceOf(typeof(Token), response, "response is Token");
        }
        
        /// <summary>
        /// Test TokensDelete
        /// </summary>
        [Test]
        public void TokensDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tokenId = null;
            //instance.TokensDelete(tokenId);
            
        }
        
        /// <summary>
        /// Test TokensList
        /// </summary>
        [Test]
        public void TokensListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? size = null;
            //int? page = null;
            //var response = instance.TokensList(size, page);
            //Assert.IsInstanceOf(typeof(TokenList), response, "response is TokenList");
        }
        
    }

}
