/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lagrello.Api;
using lagrello.Model;
using lagrello.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lagrello.Test
{
    /// <summary>
    ///  Class for testing ActivateTenantRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActivateTenantRequestTests
    {
        // TODO uncomment below to declare an instance variable for ActivateTenantRequest
        //private ActivateTenantRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ActivateTenantRequest
            //instance = new ActivateTenantRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ActivateTenantRequest
        /// </summary>
        [Test]
        public void ActivateTenantRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ActivateTenantRequest
            //Assert.IsInstanceOf(typeof(ActivateTenantRequest), instance);
        }


        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'CompanyAddress'
        /// </summary>
        [Test]
        public void CompanyAddressTest()
        {
            // TODO unit test for the property 'CompanyAddress'
        }
        /// <summary>
        /// Test the property 'CompanyCity'
        /// </summary>
        [Test]
        public void CompanyCityTest()
        {
            // TODO unit test for the property 'CompanyCity'
        }
        /// <summary>
        /// Test the property 'CompanyPostalCode'
        /// </summary>
        [Test]
        public void CompanyPostalCodeTest()
        {
            // TODO unit test for the property 'CompanyPostalCode'
        }
        /// <summary>
        /// Test the property 'CompanyCountry'
        /// </summary>
        [Test]
        public void CompanyCountryTest()
        {
            // TODO unit test for the property 'CompanyCountry'
        }
        /// <summary>
        /// Test the property 'CompanyOrgNumber'
        /// </summary>
        [Test]
        public void CompanyOrgNumberTest()
        {
            // TODO unit test for the property 'CompanyOrgNumber'
        }
        /// <summary>
        /// Test the property 'CompanyVATNumber'
        /// </summary>
        [Test]
        public void CompanyVATNumberTest()
        {
            // TODO unit test for the property 'CompanyVATNumber'
        }

    }

}
