/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lagrello.Api;
using lagrello.Model;
using lagrello.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lagrello.Test
{
    /// <summary>
    ///  Class for testing CreateTokenRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateTokenRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateTokenRequest
        //private CreateTokenRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateTokenRequest
            //instance = new CreateTokenRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateTokenRequest
        /// </summary>
        [Test]
        public void CreateTokenRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CreateTokenRequest
            //Assert.IsInstanceOf(typeof(CreateTokenRequest), instance);
        }


        /// <summary>
        /// Test the property 'TokenName'
        /// </summary>
        [Test]
        public void TokenNameTest()
        {
            // TODO unit test for the property 'TokenName'
        }
        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Test]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }

    }

}
