/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lagrello.Api;
using lagrello.Model;
using lagrello.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lagrello.Test
{
    /// <summary>
    ///  Class for testing CreateTenantRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateTenantRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateTenantRequest
        //private CreateTenantRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateTenantRequest
            //instance = new CreateTenantRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateTenantRequest
        /// </summary>
        [Test]
        public void CreateTenantRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CreateTenantRequest
            //Assert.IsInstanceOf(typeof(CreateTenantRequest), instance);
        }


        /// <summary>
        /// Test the property 'TenantName'
        /// </summary>
        [Test]
        public void TenantNameTest()
        {
            // TODO unit test for the property 'TenantName'
        }
        /// <summary>
        /// Test the property 'AdminEmail'
        /// </summary>
        [Test]
        public void AdminEmailTest()
        {
            // TODO unit test for the property 'AdminEmail'
        }

    }

}
