/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lagrello.Api;
using lagrello.Model;
using lagrello.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lagrello.Test
{
    /// <summary>
    ///  Class for testing Paging
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PagingTests
    {
        // TODO uncomment below to declare an instance variable for Paging
        //private Paging instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Paging
            //instance = new Paging();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Paging
        /// </summary>
        [Test]
        public void PagingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Paging
            //Assert.IsInstanceOf(typeof(Paging), instance);
        }


        /// <summary>
        /// Test the property 'Previous'
        /// </summary>
        [Test]
        public void PreviousTest()
        {
            // TODO unit test for the property 'Previous'
        }
        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Test]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }

    }

}
