/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lagrello.Api;
using lagrello.Model;
using lagrello.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lagrello.Test
{
    /// <summary>
    ///  Class for testing Tenant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantTests
    {
        // TODO uncomment below to declare an instance variable for Tenant
        //private Tenant instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Tenant
            //instance = new Tenant();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Tenant
        /// </summary>
        [Test]
        public void TenantInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Tenant
            //Assert.IsInstanceOf(typeof(Tenant), instance);
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Test]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'TenantName'
        /// </summary>
        [Test]
        public void TenantNameTest()
        {
            // TODO unit test for the property 'TenantName'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Test]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
        /// <summary>
        /// Test the property 'CompanyInfo'
        /// </summary>
        [Test]
        public void CompanyInfoTest()
        {
            // TODO unit test for the property 'CompanyInfo'
        }
        /// <summary>
        /// Test the property 'Activated'
        /// </summary>
        [Test]
        public void ActivatedTest()
        {
            // TODO unit test for the property 'Activated'
        }

    }

}
