/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lagrello.Api;
using lagrello.Model;
using lagrello.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lagrello.Test
{
    /// <summary>
    ///  Class for testing TotpEnableRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TotpEnableRequestTests
    {
        // TODO uncomment below to declare an instance variable for TotpEnableRequest
        //private TotpEnableRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TotpEnableRequest
            //instance = new TotpEnableRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TotpEnableRequest
        /// </summary>
        [Test]
        public void TotpEnableRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TotpEnableRequest
            //Assert.IsInstanceOf(typeof(TotpEnableRequest), instance);
        }


        /// <summary>
        /// Test the property 'Enable'
        /// </summary>
        [Test]
        public void EnableTest()
        {
            // TODO unit test for the property 'Enable'
        }

    }

}
