/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lagrello.Api;
using lagrello.Model;
using lagrello.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lagrello.Test
{
    /// <summary>
    ///  Class for testing TotpEnableResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TotpEnableResponseTests
    {
        // TODO uncomment below to declare an instance variable for TotpEnableResponse
        //private TotpEnableResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TotpEnableResponse
            //instance = new TotpEnableResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TotpEnableResponse
        /// </summary>
        [Test]
        public void TotpEnableResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TotpEnableResponse
            //Assert.IsInstanceOf(typeof(TotpEnableResponse), instance);
        }


        /// <summary>
        /// Test the property 'SecretKey'
        /// </summary>
        [Test]
        public void SecretKeyTest()
        {
            // TODO unit test for the property 'SecretKey'
        }
        /// <summary>
        /// Test the property 'QrImage'
        /// </summary>
        [Test]
        public void QrImageTest()
        {
            // TODO unit test for the property 'QrImage'
        }

    }

}
